from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import BookList, BookViewSet

# DRF router
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Existing simple list endpoint
    path('books/', BookList.as_view(), name='book-list'),

    # All routes generated by the router for BookViewSet
    path('', include(router.urls)),
]
